### ISSUE TITLE
Snake Ricochet

### ISSUE THREAD

**Issue by Jagermeister** [betterin30days/CirclingSnakes#4]
#Snake Movement Rules - No Collision
* Snakes should only be allowed to turn perpendicular to their direction.
* Snakes should not be allowed to turn before they have traveled the distance of their first segment.

**Comment by 8888** [comment]
Commit: https://github.com/betterin30days/CirclingSnakes/commit/a18412914691abef45d8dae6e49d1445ee82b45d
