### ISSUE TITLE
Fruit Collision

### ISSUE THREAD

**Issue by Jagermeister** [betterin30days/CirclingSnakes#5]
# Fruit Collision and Effect
* Snake's first segment distance to fruit being less than size of segment and fruit, shall have eaten the fruit!
  * (s)      (f)  = snake distance from fruit (50) is > snake (10) + fruit (10)
  * (sf)          = snake distance from fruit (19) is <= snake (10) + fruit (10)
* Fruit on collision should be removed and server notified to notify all other players
* Snake on collision with fruit should have an effect applied (segment added?)

**Comment by 8888** [comment]
Commit: https://github.com/betterin30days/CirclingSnakes/commit/a18412914691abef45d8dae6e49d1445ee82b45d
